language: java
jdk:
- oraclejdk8
script: ant build

addons:
  sonarcloud:
    organization: "danielcodin-github" # the key of the org you chose at step #3
    token:
      secure: 5367f0121b7d30d4127458f1192356d2682a5809 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
